// Generated by ts-to-zod
import { z } from "zod";

export const asConfigMazeSchema = z.object({
    buff_1: z.array(z.number()),
    buff_2: z.array(z.number()),
    maze_buff: z.number()
});

export const pfConfigMazeSchema = z.object({
    buff: z.array(z.number()),
    maze_buff: z.number()
});

export const mocConfigMazeSchema = z.object({
    maze_buff: z.number()
});

export const avatarConfigMazeSchema = z.object({
    maze_buff: z.array(z.number())
});

export const stageConfigMazeSchema = z.object({
    stage_id: z.number(),
    stage_type: z.string(),
    level: z.number(),
    monster_list: z.array(z.record(z.string(), z.number()))
});

export const skillConfigMazeSchema = z.object({
    max_level: z.number(),
    index_slot: z.number()
});

export const configMazeSchema = z.object({
    Avatar: z.record(z.string(), avatarConfigMazeSchema),
    MOC: z.record(z.string(), mocConfigMazeSchema),
    AS: z.record(z.string(), asConfigMazeSchema),
    PF: z.record(z.string(), pfConfigMazeSchema),
    Stage: z.record(z.string(), stageConfigMazeSchema),
    Skill: z.record(z.string(), skillConfigMazeSchema)
});
