// Generated by ts-to-zod
import { z } from "zod";

export const monsterChildSchema = z.object({
    Id: z.number(),
    AttackModifyRatio: z.number(),
    DefenceModifyRatio: z.number(),
    EliteGroup: z.number(),
    HPModifyRatio: z.number(),
    SpeedModifyRatio: z.number(),
    SpeedModifyValue: z.number().nullable(),
    StanceModifyRatio: z.number(),
    HardLevelGroup: z.number(),
    StanceWeakList: z.array(z.string())
});

export const monsterValueSchema = z.object({
    Rank: z.string(),
    AttackBase: z.number(),
    DefenceBase: z.number(),
    HPBase: z.number(),
    SpeedBase: z.number(),
    StanceBase: z.number(),
    StatusResistanceBase: z.number(),
    child: z.array(monsterChildSchema)
});
