// Generated by ts-to-zod
import { z } from "zod";

export const partDataSchema = z.object({
    Name: z.string(),
    Desc: z.string(),
    Story: z.string()
});

export const requireBonusSchema = z.object({
    Desc: z.string(),
    ParamList: z.array(z.number())
});

export const relicDetailSchema = z.object({
    Name: z.string(),
    Icon: z.string(),
    Parts: z.record(z.string(), partDataSchema),
    RequireNum: z.record(z.string(), requireBonusSchema),
    Bonus: z.record(z.string(), z.array(z.object({
        type: z.string(),
        value: z.number()
    })))
});
